### ISSUE TITLE
`dance.openMenu` doesn't work on non-editor vscode pages

### ISSUE THREAD

**Issue by cupnoodles14** [71/dance#112]
hello! thanks for the great extension.

i'm really liking `dance.openMenu`, i use it as a leader key with submenus and stuff. one small problem i have is that it doesn't work on some vscode pages: the welcome page, the fallback page (when no files are open), extension description pages etc.

i was planning to use it with a `when` expression that looks like this: `"when": "!inputFocus || editorTextFocus && dance.mode == 'normal'"` (not sure if this would actually work properly), but it doesn't work even without a `when` expression.

```json
{
    "key": "space",
    "command": "dance.openMenu",
    "args": { "menu": "leader" }
},
```

`dance.toggle` works everywhere though. from what i see, the extension registers it a bit differently but i don't have much experience with JS/vscode extensions to produce a sane PR :smirk:

**Comment by 71** [comment]
Hey there! The issue is that all commands (except for `dance.toggle`) [do not run if there is no active text editor](https://github.com/71/dance/blob/021a1fa334efcc035a9e1c1cf618358412608504/src/commands/index.ts#L363-L364). In most cases, it doesn't make sense to run a command if there is no active editor, so all commands actually expect an editor. However it does look like `openMenu` specifically could be useful outside of text editors. I have a solution in mind but it's a little hacky. I'll investigate.

**Comment by nwwdles** [comment]
thanks, i've built it from master and it works great!

here's [an excerpt of my current config](https://gist.github.com/d20c87e850917b8b68fc271f2841836d) in case anyone might be interested.

**Comment by 71** [comment]
Nice. There are a few interesting things there that I might reuse, thanks for sharing!

**Comment by pomdtr** [comment]
I love it. Quite similar to the spacemacs menu :)

**Comment by tshort** [comment]
Agreed. Great stuff!

**Comment by petertheprocess** [comment]
Sorry for digging this issue 3 years later. 
But I have found that if I add the delay arg, the openMenu doesn't work on non-editor pages as well. It seems `showMenuAfterDelay` api requires the currentContext to cancel menu showing, but non-editor doesn't have a context.
