### ISSUE TITLE
Exiting insert mode when Escape and Capslock are swapped

### ISSUE THREAD

**Issue by Schmiddiii** [71/dance#119]
Hi,
I have swapped my Escape and Capslock using ```setxkbmap -option caps:swapescape```.
What i would expect is that I can leave insert mode using the Capslock-Key, but nothing happens. To leave insert mode I need to press the Escape button (that is remapped to be Capslock).
Furthermore when leaving insert mode using Escape, Capslock still gets activated (writing uppercase letters when typing normal).

Other keybindings using the Escape character seem to work (e.g. closing "Show all Commands" window, closing "Find" window).

I have not changed any keybindings yet.

I am currently using VSCodium (1.50) so it might also be an error in VSCodium. 
Currently using Ubuntu 18.04.

**Comment by 71** [comment]
Hey,

Due to the way keybindings are used, Dance doesn't handle keys at all, it just receives commands triggered by VS Code according to the keybindings. I'm guessing it doesn't work well with remapped escape keys.

You can try the visual keybindings editor and then look at the resulting JSON file; it will contain the key that should be given for that input.

**Comment by Schmiddiii** [comment]
After a little bit more searching I found that it is an error in VSCode and has a workaround (https://github.com/microsoft/vscode/issues/23991).

Thank you.

**Comment by 71** [comment]
Alright, I'm glad you found a fix.
