### ISSUE TITLE
Discoverability on Marketplace

### ISSUE THREAD

**Issue by timjs** [71/dance#12]
First, I have to say how super awesome I find this plugin! It is exactly what I was looking for. Wanted to have this for a long time. Combines best of all the worlds of VSCode and Kakoune and Vim :-)

Took me some time to find this plugin however. Think adding the word "Kakoune" to the description will make the plugin way more discoverable on the marketplace!

**Comment by 71** [comment]
I'm glad you like it!

This is done on purpose -- I don't think it's close enough to what Kakoune offers to be advertised as an extension yet. In fact, I only released the plugin in the marketplace because it was asked of me, but I don't think its quality is good enough for a "public" release yet (see #2, it has more context).

**Comment by timjs** [comment]
Ah, I understand. I'll do some testing this week and will let you know if I run into something to increase quality!
