### ISSUE TITLE
<c-[> changes indentation instead of being treated as <esc>

### ISSUE THREAD

**Issue by Parasrah** [71/dance#133]
I personally use `<c-[>` instead of `<esc>`, which currently triggers de-indentation instead of leaving insert mode. I can probably figure out a way to fix this via keybindings in vscode, but might also be good to add this as a setting in the extension

**Comment by 71** [comment]
Sorry for the late response. This is a good idea, but I'm not sure I want the extension to override an existing VS Code keybinding when there is already a keybinding `<esc>` that works. As you said we can always change this in the keybindings in VS Code so I don't think this is an issue.

If anybody sees this issue and also thinks `<c-[>` should be overridden by default, please re-open this issue and I'll reconsider. I'm a little biased in my choice because pressing `<c-[>` is impossible with my current keyboard layout, so I've never used it.
