### ISSUE TITLE
single char selection highlights messed in character Selection Behavior

### ISSUE THREAD

**Issue by cccooo** [71/dance#134]
In character Selection Behavior,the caret always selects the character before,causes vscode highlight all the character selected,it is very messed when caret continue moving.
can I disable single char selection highlights,but keep word (more than one character selected) hightlights? word highlights are very useful.
Now  I have to changed to caret Selection Behavior,but it is not convenient for char replace or change and other expand selection.
![图片](https://user-images.githubusercontent.com/2192585/104078673-531ee500-525a-11eb-8e34-679e8d3da10a.png)

**Comment by 71** [comment]
Unfortunately it's a little tough to implement this because it requires changing VS Code settings, which leads them to being written to a configuration file.

Out of curiosity, I just tried implementing this by toggling `editor.selectionHighlight` off when the selection is 1-character long, but it seems to cause issues within VS Code (such as 1-char selection highlights staying after selecting something else, and `editor.selectionHighlight` not being taken into consideration outside of `settings.json`). Part of me says this sounds like a good opportunity to contribute a fix to VS Code, but I doubt I'll have time to do that before long.

**Comment by cccooo** [comment]
Thank you for taking the time on this issue.
Maybe  the vscodevim extension solution is a good reference:
It doesn't need users to switch the selectionhighlight configuration,vim extension`s caret selects current char，but highlights whole word
![图片](https://user-images.githubusercontent.com/2192585/108295011-e4766500-71d1-11eb-86f3-de6a2901cfb4.png)

**Comment by 71** [comment]
The difference being that VSCodeVim operates on positions, like VS Code. So in your screenshot, you're using a block cursor but really no character is selected (your selection is empty).

VSCodeVim still works fine because it hard-cases situations where the selection is empty (at least that's my guess). We could do this with Dance as well, but when we first started the implementation of the "character" selection mode we figured it would be better to always make sure the selection is non empty instead of hard casing commands for empty selections, which would probably be more complicated since Kakoune operates on selections a lot.

**Comment by 71** [comment]
The `character` selection behavior was reviewed for the 0.5 update, and no longer suffers from this problem. If you'd like to try it out, it's on the `master` branch (I will upload it on the marketplace once I'm confident there are no more terrible bugs).
