### ISSUE TITLE
Dance 0.5.0: High input lag on undo

### ISSUE THREAD

**Issue by pomdtr** [71/dance#151]
https://user-images.githubusercontent.com/17577332/117544983-14d8dd00-b024-11eb-8f52-f36cc499017b.mp4

**Comment by 71** [comment]
Looks like a keybinding issue:
- Using `c-z` is instant.
- Using `u` is slow.
- Using command palette > `Undo` is instant.
- Using command palette > `Dance > Undo` is instant.

The issue here is the context change in VS Code (going from `insert` mode to `normal` mode and then issuing the undo). If you wait a little bit after going back to `normal` mode before pressing `u`, the `undo` is instant. It's been an issue since the beginning, but I bet that the greater amount of commands is putting more pressure on it now and making the slowdowns more significant.

Note to self:
- Investigate if logic within VS Code can be improved.
- Investigate if adding conditions to command palette items makes it worse.

**Comment by 71** [comment]
Welp: an `AutoDisposable` was disposed of when switching to normal, which disposed of a `StyledSet`, which disposed of the `AutoDisposable`, etc. After debugging this, I think that there was some infinite recursion that somehow completed in some instances, or crashed the process in others. It's fixed now, and context switches should be fast again.

Thanks for all the bug reports!
