### ISSUE TITLE
Is there a way to turn off Hidden Selection Indicator?

### ISSUE THREAD

**Issue by huytd** [71/dance#184]
First of all, thank you so much for making this plugin, I love Kakoune, and being able to have a Kakoune-like experience in VSCode is awesome!

For the hidden selection indicator, this feature is good but I tend to use pageUp/pageDown a lot and sometimes the indicator leaves some trace on the screen for a while, making the scrolling experience not smooth, and I rarely need it for now.

I tried to turn it off by setting `hiddenSelectionsIndicatorsDecoration` to `null` or remove it, but nothing works:

```
"": {
  "hiddenSelectionsIndicatorsDecoration": null
}
```

Is this the right way to turn it off?

**Comment by 71** [comment]
Looks like there is a bug in VS Code where it does not properly support the `""` key in settings (from the side of the extension, we don't receive configuration change events when it changes, and when explicitly reading its value VS Code always returns its default value). Looks like https://github.com/microsoft/vscode/issues/126972.

**Comment by 71** [comment]
There was also an issue within Dance where the indicator couldn't be disabled. This was fixed in 08199c526eda61ab15cc605beb3cabc4c17e644e.

While waiting for https://github.com/microsoft/vscode/issues/126972 to get fixed, you can specify this for each mode individually:

```json
"dance.modes": {
  "normal": {
    "hiddenSelectionsIndicatorsDecoration": {}
  },
  "insert": {
    "hiddenSelectionsIndicatorsDecoration": {}
  },
}
```

Note that `{}` is used rather than `null`. In Dance modes configuration, `null` means "inherit from the `""` mode", so we need another value to represent "disable this."

**Comment by huytd** [comment]
Awesome, thank you so much!

**Comment by 71** [comment]
@BeastyBlacksmith You can set the `backgroundColor` and `borderColor` properties:

```json
"dance.modes": {
    "": {
        "hiddenSelectionsIndicatorsDecoration": {
            "backgroundColor": "#00000000",
            "borderColor": "#00000000"
        }
    }
},
```
