### ISSUE TITLE
m doen't include <> type of brackets

### ISSUE THREAD

**Issue by jbytes1027** [71/dance#191]
in kakoune the angle brackets <> can be selected with the m key

**Comment by 71** [comment]
I'm not sure what's best here. On one hand `<>` is indeed useful when selecting generics in C-like languages, but on the other hand it very often conflicts with comparison and bitwise operators. I remember being bothered more often than not because a comparison had matched instead of a bracket when using `m`, which is why the default doesn't match `<>`.

I believe it would be fair to discuss the defaults here, if you think my reasoning is wrong. In the meantime, you can override this behavior by changing the keybindings as such:

```jsonc
{
  "key": "m",
  "command": "dance.seek.enclosing",
  "args": {
    "pairs": [
      "<", ">",
      "\\{", "\\}",
      // ...
    ],
  },
  "when": "editorTextFocus && dance.mode == 'normal'",
},
// ...
```

**Comment by jbytes1027** [comment]
I think context based matching would be confusing and overcomplicated, which is the kakoune philosophy, but what I am realizing is that this project as a whole conflicts with the kakoune philosophy of simplicity. Similarly, I think brackets are brackets and dance shouldn't be tailored to be more or less convenient for a specific type of syntax like bitwise operators and comparisons.

**Comment by jbytes1027** [comment]
Not invested anymore
