### ISSUE TITLE
Add mention of the `extensions.experimental.affinity` setting in the doc.

### ISSUE THREAD

**Issue by pomdtr** [71/dance#282]
VS Code added support for running extension in their own threads to reduce lag in critical extensions.

See https://github.com/vscode-neovim/vscode-neovim#installation

It might be worth to mention it in the readme ?

**Comment by 71** [comment]
Oh, I didn't know about that, thanks for the pointer! I'll try to experiment with it to see if it's useful. I'm not sure it will help as much as the Vim extensions though, since Dance doesn't override the `type` command (and instead uses keybindings, which IIUC are "compiled" based on context by the main VS Code process, so using a different thread wouldn't help).

**Comment by 71** [comment]
Btw I've been using this setting but I don't know if it led to any improvements. If we get feedback that it helps I'll consider mentioning it in the docs!
