### ISSUE TITLE
"Insert after" doesn't want to work

### ISSUE THREAD

**Issue by merlindru** [71/dance#285]
I'm not sure if I misunderstood anything about how Kakoune works (I've only ever used Dance), but pressing `a` should put me into insert mode _after_ the selection, right?

On my end, `a` and `i` do the same thing. This happens both with and without `"selectionBehavior": "character"`.

Any idea about what could be going on?

Thanks for building this amazing extension!

**Comment by 71** [comment]
Hi, and thanks for the report! Even when you have long selections `a` goes to the beginning? Are you sure that you didn't override was `a` does in VS Code keybindings? I don't really know where the error can come from, I think your best shot is to clone the Dance repo, open it in VS Code, and run the extension. This will allow you to debug it (with breakpoints) and see what happens when you press `a`.

**Comment by merlindru** [comment]
Thanks for the quick reply! When I have a long beginning, a does go to the **end** of that selection, but inserts the character **before** the last char of the selection. Maybe this is intended?

```
<selection>asdfasdfasdf</selection>
```

if this ^ is my selection, and I press `a`, this happens:

```
asdfasdfasd<cursor>f
```

but I expected this:

```
asdfasdfasdf<cursor>
```

Which made me think `a` and `i` did the same thing. They don't! But it still seems unusual

**Comment by 71** [comment]
And this also happens with `"selectionBehavior": "caret"`? My guess is that you either have `"selectionBehavior": "caret"` with `"cursorStyle": "block"`, or `"selectionBehavior": "character"` with `"cursorStyle": "line"`.

**Comment by merlindru** [comment]
Oh! That clears it up!

This was my config:

```json
"dance.modes": {
	"input": {},
	"insert": {
		"selectionBehavior": "character"
		},
	"normal": {
		"cursorStyle": "block",
		"selectionBehavior": "character"
	}
},
```

When using `"selectionBehavior": "caret"` it works as expected. Is this me misunderstanding how it's supposed to work/how kak works, or is this a bug?

For example:

```
"|selectionBehavior": "caret"
```

![image](https://user-images.githubusercontent.com/85179170/203989719-bdea186b-3286-4dfc-81dd-8a4b2751dcc8.png)


Pressing `w` does this:

```
"<anchor>selectionBehavio|r<anchor>": "character"
```

![image](https://user-images.githubusercontent.com/85179170/203989745-24456a65-cd52-47ae-bf75-eb5e7dedf857.png)

**Comment by 71** [comment]
Dance `"character"` selection behavior is meant to work with `"block"` cursor style because it internally converts a selection like `selectionBehavio|r` (as seen by VS Code) into `selectionBehavior|` (as seen by Dance) because with a block cursor, it looks like `selectionBehavio[r]` is selected even though VS Code considers that the selection ends _before_ `r`. Perhaps a warning should be emitted that `"cursorStyle": "line"` (the default) doesn't work well with `"selectionBehavior": "character"`.

Note that Kakoune doesn't have that concept; `"caret"` selection behavior is simply the native VS Code selection behavior, and `"character"` selection behavior is an emulation of how Kakoune works for Dance commands (because in VS Code `fo[o]` (with the block on the last `o` only considers `fo` in the collection, whereas in Kakoune it considers `foo`). Dance used to work differently (by modifying the style of the collection instead of using a `"block"` character style, avoiding having to translate selections in some cases), but this led to even more issues.

**Comment by merlindru** [comment]
@71 I disabled `"cursorStyle": "block"` just for the sake of the example -- I've posted the settings I'm usually using above :P


Again, I'm not sure how it's in Kak, but with Helix, pressing `a` lands my cursor to the right side of the block. Something like this: 
![image](https://user-images.githubusercontent.com/85179170/204002459-35173fb0-1eb8-4f83-a654-f8fef9cda5a6.png)

With Dance, it lands me to the **left side of the e**, with the settings I posted above (block + character)

**Comment by merlindru** [comment]
That's why I filed this issue in the first place, it looks just like it does with e.g. Helix (my block cursor is over the character) but when I press `a`, Dance acts as if it's not

**Comment by 71** [comment]
I tried it on my end and pressing `a` in your example on Dance (block + character) goes to the right side of `e` as expected. I'm not sure what's going wrong on your end, so I'd suggest debugging Dance when you press `a`. You can put a breakpoint [here](https://github.com/71/dance/blob/7d73bfc0245a8ce447323bb456fa3e8f8f977eda/src/commands/index.ts#L89) and look at various locals to see what command is being executed; in theory, its name should be [`dance.modes.insert.after`](https://github.com/71/dance/blob/7d73bfc0245a8ce447323bb456fa3e8f8f977eda/src/commands/modes.ts#L24).

**Comment by merlindru** [comment]
That's odd. Thank you for all your help! :)

If I end up debugging it, I'll post what I've found in here

**Comment by 71** [comment]
@merlindru In case you didn't see it before replying, I edited my comment with a possible solution.

**Comment by merlindru** [comment]
Thanks! Missed that. Will try

**Comment by merlindru** [comment]
Removing `"selectionBehavior": "character"` from `dance.modes.insert` fixed it! Thank you so much 😄

**Comment by merlindru** [comment]
Can't believe I didn't try that first. Using character selection behavior in insert mode doesn't make any sense.
