### ISSUE TITLE
not able to yank from documentation hover pop up

### ISSUE THREAD

**Issue by josephs07** [71/dance#313]
### Discussed in https://github.com/71/dance/discussions/312

<div type='discussions-op-text'>

<sup>Originally posted by **josephs07** October  2, 2023</sup>
How to yank contents from documentation hover?
VS code by default lets us copy contents from the documentation popup. While using dance this behavior is not working. This is necessary while using languages that support keyword arguments. 

![image](https://github.com/71/dance/assets/23273684/126da9c1-d825-4175-a7fc-d54687ec159e)
</div>

**Comment by 71** [comment]
Hey, sorry for the delay!

Do you want to yank by pressing `y` or `ctrl/cmd-c`? I tested the latter on both the release and pre-release versions of Dance, and didn't encounter any problem. The former shouldn't work, as Dance only defines keybindings within active editors. With that said, since popups cannot be edited (i.e. in a way, can only be in `normal` mode), I'm open to make a limited set of keybindings (e.g. `y`) available in these popups (if VS Code permits it to begin with).

**Comment by josephs07** [comment]
Sorry! my bad. The `ctrl/cmd+c` is working inside the documentation pop up.  I thought its not working coz I was trying to paste with `ctrl/cmd+v` which is overridden by dance.
It will be helpful if we can use `y` to yank from the popups instead of `ctrl/cmd+c` 
Btw dance is awesome. Thanks a lot

**Comment by 71** [comment]
I looked into using `y` to yank in popups, and AFAIK there is no way for extensions to query the selected text outside of editors, so I don't think this is possible...

Buuut if you're fine with a fairly limited solution, you may define the following keybinding:

```jsonc
  {
    "key": "y",
    "command": "editor.action.clipboardCopyAction",
    "when": "editorHoverVisible",
  },
```

It will run `editor.action.clipboardCopyAction` (the default `ctrl+c` action) when `y` is pressed and the hover view is visible.

It doesn't use Dance at all (so registers are not used, everything is copied straight to the system clipboard) so I don't think I will add it to the built-in keybindings, but it might be useful.
