### ISSUE TITLE
Rotate selections is order-dependent

### ISSUE THREAD

**Issue by MaxCross2500** [71/dance#322]
All `rotate selections` commands rotate selections in order of wich they were added, instead of visual order.
(This + the fact that `add next match` command add selection in reverse order results in quite unintuitive behaviour).
Is this intended behaviour? (I don't have kakoune, so I don't now how it works in it). If it is, can we at least get alternate commands to rotate selection in visual order, so it would be possible to rebind?

**Comment by 71** [comment]
This ended up being more complex than I thought.

The problem is that Kakoune and Helix only seem to care about which selection is the main one. When rotating selections, they only have to update that index, and in the UI this is reflected by having the main selection moving. When rotating contents, they can rotate contents clockwise visually, and since there is only one index to consider when rotating selections, they can perform the same update on the main index integer and that's the end of that.

The problem is that, in Dance, selections are numbered. When rotating selections, it makes sense to rotate them by index rather than by visual position. Sorting them by visual position _while maintaining their positions_ is harder.

This is a breaking change, but I guess the way to go is to rotate selections visually regardless of their actual position, and then to restore their indices. This allows us to stay consistent with rotation of selection contents.

**Comment by 71** [comment]
@MaxCross2500 Yes, that's right. I probably worded the above message wrong. The way indices interact with order in the document was hard to get right and I wasn't sure there was an approach that could both maintain the order of current selections (wrt indices) _and_ order of the document, but thankfully I found one.
