### ISSUE TITLE
`gl` and `gh` do not set "desired column"

### ISSUE THREAD

**Issue by J-Fields** [71/dance#43]
Hey there! In VSCodeVim we keep track of the column that the cursor *wants* to be on in addition to the one it's actually on (`VimState.desiredColumn`). So `$` will set the desired column to `MAX_INT` - that way, motions like `j` and `k` will go to the end of the line, when coming from a shorter line.

It does seem dance has that concept, but `gh` and `gl` don't set it to `0` and `MAX_INT` like kakoune does.

(Very cool extension, by the way! I'll definitely try to find some time to contribute)

**Comment by 71** [comment]
Thanks for the report! There is a little bit of code to handle that, although it's somewhat messy and indeed does not handle all cases. I'll try to take care of it at some point.

**Comment by J-Fields** [comment]
Mind pointing me toward that section? Maybe I'll fix this case or at least clean it up if I get a chance.

**Comment by 71** [comment]
Most of the cases are in [`move.ts`](https://github.com/71/dance/blob/master/src/commands/move.ts), and more precisely using [`preferredColumnsPerEditor`](https://github.com/71/dance/blob/747fb49e99c93ad8055e39471aff34be8abe70e2/src/commands/move.ts#L16). The problem is that `preferredColumnsPerEditor` is not exported, so e.g [`gl`](https://github.com/71/dance/blob/747fb49e99c93ad8055e39471aff34be8abe70e2/src/commands/goto.ts#L33) (in `goto.ts`) cannot set the relevant `preferredColumnsPerEditor` value.

`selectToLineEnd` and `selectToLineEndExtend` in `move.ts` would also need to be changed to set the relevant `preferredColumnsPerEditor` to `INT_MAX`.

**Comment by 71** [comment]
This was fixed in `unstable`. If there are other instances where we're forgetting to set `preferredColumns`, please let me know below.
