### ISSUE TITLE
multiple selection yank

### ISSUE THREAD

**Issue by pomdtr** [71/dance#47]
In dance deleting and pasting :

1
2
3

produce:

1
1
1

However in vscode multiple selection and kakoune :

1
2
3

is restored.

**Comment by nightscape** [comment]
As far as I can see, the problem is that the [`pasteAfter` command uses the `getContentToPaste` method](https://github.com/71/dance/blob/master/src/commands/changes.ts#L65), which [only takes the first selection](https://github.com/71/dance/blob/master/src/commands/changes.ts#L61).
The question is what should happen when selections don't contain line endings.
My current thinking is (and maybe @pomdtr you can check that in Kakoune, I'm on Windows unfortunately) that one could insert all selections in sequence, but add cursors before or after every pasted element. That way, one could still quickly insert new-lines by pressing Enter.
