### ISSUE TITLE
`x` advances two lines at a time 

### ISSUE THREAD

**Issue by tshort** [71/dance#96]
This is on master. `x` advances two lines instead of one. `X` also advances two lines the first time it is run. Plus, unlike kak, `x` selects the line, and the cursor is on the next line.

**Comment by tshort** [comment]
There's a test that covers this situation. I'm not sure how to run the tests. I tried `npm run test`, and it failed.

**Comment by tshort** [comment]
If "selection behavior" is set to "character", this issue is fixed. (That's my preference anyway.)

**Comment by 71** [comment]
This is partially fixed in e3764d19e60147a94346517b1dbd38576002f5fa. The part about `the cursor in on the next line` should be discussed, though. When you select the entire line in Kakoune, the line break character is also selected. However, the only way to select the line character in VS Code is to select until `(line + 1, 0)` (that's also how VS Code describes full lines internally, btw; `TextLine.rangeIncludingLineBreak` returns `((line, 0), (line + 1, 0))`.

This behavior of selecting until before the first character of the next line has pros and cons. It's a little hard to get used to, but I think the pros outweigh the cons.

**Comment by yuchenshi** [comment]
Closing this since keeping the "cursor" on the next line is the only way to go in VSCode for selecting a full line including the line break. I've opened #102 to track adding a better cursor indicator so it looks and feels less weird.
