### ISSUE TITLE
<a-i> is not working on macOS

### ISSUE THREAD

**Issue by louy2** [71/dance#99]
`<a-i>` inserts a unicode hat modifier, instead of starting select inside. Any workarounds?

**Comment by vbn** [comment]
Not much `dance` extension can do. It's a [VSCode bug](https://github.com/microsoft/vscode/issues/41024). Actually, it's inherited from this [chromium bug](https://crbug.com/887519).

I have "worked around" this bug by using [Karabiner-Elements](https://karabiner-elements.pqrs.org/) to transform `<alt>+i` into `<alt>+<ctrl>+i`. In VSCode, I updated mapping for `dance` keyboard shortcuts to use `<alt>+<ctrl>+i` for `Select Inner Object`. All this because I didn't want to change my Kakoune muscle memory.

If you don't care about using the exact same shortcut, switching to a non-buggy shortcut would be the easiest thing to do.

**Comment by 71** [comment]
@vbn Thanks for the explanation. Redirecting to the main issue for keybindings in macOS: #18.

**Comment by louy2** [comment]
@vbn Thank you! I think I might just set it to `<cmd-i>`.
